export const ALL_SOFTWARES = [
  'Photoshop',
  'Illustrator', 
  'InDesign',
  'After Effects',
  'Premiere Pro',
  'Figma',
  'Sketch',
  'Blender',
  'Maya',
  '3ds Max',
  'Cinema 4D',
  'Lightroom',
  'CorelDRAW',
  'AutoCAD',
  'SolidWorks',
  'Revit',
  'SketchUp',
  'Unity',
  'Unreal Engine',
  'DaVinci Resolve',
  'Final Cut Pro',
  'Procreate',
  'Affinity Designer',
  'Affinity Photo',
  'Canva Pro',
  'Indesign',
  'Premiere',
  'Audition',
  '3ds Max (AR)',
  'V-ray',
  'Lumion',
  'Autocad',
];